CREATE TABLE `COLLEAGUES` (
  `ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `TICKETS` (
  `ID` INT(11) unsigned NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(255),
  `REPORTER_ID` INT(11) unsigned,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`REPORTER_ID`) REFERENCES `COLLEAGUES`(`ID`)
) ENGINE=InnoDB;

CREATE TABLE `COMMENTS` (
  `ID` INT(11) unsigned NOT NULL AUTO_INCREMENT,
  `TEXT` VARCHAR(255),
  `AUTHOR_ID` INT(11) unsigned,
  `TICKET_ID` INT(11) unsigned,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`AUTHOR_ID`) REFERENCES `COLLEAGUES`(`ID`),
  FOREIGN KEY (`TICKET_ID`) REFERENCES `TICKETS`(`ID`)
) ENGINE=InnoDB;
